SUPABASE_URL = "https://iiozozbdukitwgjrtbvg.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpb3pvemJkdWtpdHdnanJ0YnZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjkyMDAsImV4cCI6MjA2ODcwNTIwMH0.PghuvE2ZnJV1hqcVw6lakFtgzLZzL-F-pakAm-qbQCE"

BITRIX_HASH_USER = "22"
BITRIX_HASH_ACESSO = "ok80wjow5agq1ytp"
TOKEN_BI_CONNECTOR = "vy4ucBBd0LeZND1RQ05yWa11pq6Sx2DRbr"

AZURE_TENANT_ID     = ""
AZURE_CLIENT_ID     = ""
AZURE_CLIENT_SECRET = ""
EMAIL_USER          = "comissoes@investsmart.com.br"